"""Repository rule that generates toolchain() declarations."""

_TOOLCHAIN_BUILD_HEADER = """\
# Generated by rules_zig module extension. DO NOT EDIT.

package(default_visibility = ["//visibility:public"])
"""

_TOOLCHAIN_BUILD_TEMPLATE = """\
toolchain(
    name = "{name}",
    exec_compatible_with = [
        "{os_constraint}",
        "{cpu_constraint}",
    ],
    toolchain = "@{repo_name}//:zig_toolchain_impl",
    toolchain_type = "@rules_zig//zig:toolchain_type",
)
"""

def _zig_toolchains_repo_impl(ctx):
    lines = [_TOOLCHAIN_BUILD_HEADER]

    for i in range(len(ctx.attr.toolchain_names)):
        lines.append(_TOOLCHAIN_BUILD_TEMPLATE.format(
            name = ctx.attr.toolchain_names[i],
            repo_name = ctx.attr.toolchain_repo_names[i],
            os_constraint = ctx.attr.os_constraints[i],
            cpu_constraint = ctx.attr.cpu_constraints[i],
        ))

    ctx.file("BUILD.bazel", content = "\n".join(lines))

zig_toolchains_repo = repository_rule(
    implementation = _zig_toolchains_repo_impl,
    attrs = {
        "toolchain_names": attr.string_list(mandatory = True),
        "toolchain_repo_names": attr.string_list(mandatory = True),
        "os_constraints": attr.string_list(mandatory = True),
        "cpu_constraints": attr.string_list(mandatory = True),
    },
    doc = "Generates a repository with toolchain() declarations for Zig SDKs.",
)
